name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace localhost URLs in Manifest
        run: sed -i 's|https://localhost:3000|https://alansynn.github.io/michael|g' manifest.xml
        working-directory: ${{ github.workspace }} # Ensure it runs in the repo root

      - name: Remove [Local] suffix from Manifest
        run: sed -i 's|Michael \\[Local\\]|Michael|g' manifest.xml
        working-directory: ${{ github.workspace }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build add-in
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          commit_message: ${{ github.event.head_commit.message }}